name: Check
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: "zulu"
    - name: Build with testing
      run: ./gradlew --stacktrace check
